// @generated by tools/build-play-js.ts
// Source: play/src/browser/Ballot.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/Ballot.ts
  function ScoreBallot(config) {
    var self = this;
    config = config || {};
    config.bg = "img/ballot_range.png";
    Ballot.call(self, config);
    self.boxes = {
      square: self.createRate(133, 100, 0),
      triangle: self.createRate(133, 143, 3),
      hexagon: self.createRate(133, 184, 1),
    };
    self.update = function (ballot) {
      for (var cID in ballot) {
        var score = ballot[cID];
        self.boxes[cID].gotoFrame(score - 1);
      }
    };
  }
  function ApprovalBallot(config) {
    var self = this;
    config = config || {};
    config.bg = "img/ballot_approval.png";
    Ballot.call(self, config);
    self.boxes = {
      square: self.createBox(26, 98, 0),
      triangle: self.createBox(26, 140, 1),
      hexagon: self.createBox(26, 184, 0),
    };
    self.update = function (ballot) {
      var vote = ballot.vote;
      for (var box in self.boxes) {
        self.boxes[box].gotoFrame(0);
      }
      for (var i = 0; i < ballot.approved.length; i++) {
        var candidate = ballot.approved[i];
        self.boxes[candidate].gotoFrame(1);
      }
    };
  }
  function RankedBallot(config) {
    var self = this;
    config = config || {};
    config.bg = "img/ballot_ranked.png";
    Ballot.call(self, config);
    self.boxes = {
      square: self.createBox(26, 98, 0),
      triangle: self.createBox(26, 140, 1),
      hexagon: self.createBox(26, 184, 0),
    };
    self.update = function (ballot) {
      for (var i = 0; i < ballot.rank.length; i++) {
        var candidate = ballot.rank[i];
        var frame = 2 + i;
        self.boxes[candidate].gotoFrame(frame);
      }
    };
  }
  function PluralityBallot(config) {
    var self = this;
    config = config || {};
    config.bg = "img/ballot_fptp.png";
    Ballot.call(self, config);
    self.boxes = {
      square: self.createBox(26, 98, 0),
      triangle: self.createBox(26, 140, 1),
      hexagon: self.createBox(26, 184, 0),
    };
    self.update = function (ballot) {
      var vote = ballot.vote;
      for (var box in self.boxes) {
        self.boxes[box].gotoFrame(0);
      }
      self.boxes[vote].gotoFrame(1);
    };
  }
  function Ballot(config) {
    var self = this;
    self.dom = document.createElement("div");
    self.dom.id = "ballot";
    self.dom.style.backgroundImage = "url(" + config.bg + ")";
    self.createSprite = function (config2) {
      var sprite = {};
      sprite.dom = document.createElement("div");
      sprite.dom.setAttribute("class", "ballot_sprite");
      sprite.dom.style.backgroundImage = "url(" + config2.img + ")";
      sprite.dom.style.width = config2.w + "px";
      sprite.dom.style.height = config2.h + "px";
      sprite.dom.style.left = config2.x + "px";
      sprite.dom.style.top = config2.y + "px";
      self.dom.appendChild(sprite.dom);
      sprite.gotoFrame = function (frame) {
        sprite.dom.style.backgroundPosition =
          "0px -" + frame * config2.h + "px";
      };
      sprite.gotoFrame(config2.frame);
      return sprite;
    };
    self.createBox = function (x, y, frame) {
      return self.createSprite({
        img: "img/ballot_box.png",
        x,
        y,
        w: 50,
        h: 50,
        frame,
      });
    };
    self.createRate = function (x, y, frame) {
      return self.createSprite({
        img: "img/ballot_rate.png",
        x,
        y,
        w: 225,
        h: 50,
        frame,
      });
    };
  }
  globalThis.ScoreBallot = ScoreBallot;
  globalThis.ApprovalBallot = ApprovalBallot;
  globalThis.RankedBallot = RankedBallot;
  globalThis.PluralityBallot = PluralityBallot;
  globalThis.Ballot = Ballot;
})();
