// @generated by tools/build-play-js.ts
// Source: play/src/browser/Buttons.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/Buttons.ts
  function ButtonGroup(config) {
    var self = this;
    self.config = config;
    self.buttonConfigs = config.data;
    self.onChoose = config.onChoose;
    self.dom = document.createElement("div");
    self.dom.setAttribute("class", "button-group");
    self.label = document.createElement("div");
    self.label.setAttribute("class", "button-group-label");
    self.label.innerHTML = config.label;
    self.dom.appendChild(self.label);
    self.buttons = [];
    self.onToggle = function (button2, buttonData) {
      for (var i2 = 0; i2 < self.buttons.length; i2++)
        self.buttons[i2].turnOff();
      button2.turnOn();
      self.onChoose(buttonData);
    };
    self.highlight = function (propName, propValue) {
      for (var i2 = 0; i2 < self.buttons.length; i2++)
        self.buttons[i2].turnOff();
      var theButton = self.buttons.filter(function (button2) {
        var config2 = button2.config;
        return config2[propName] == propValue;
      })[0];
      theButton.turnOn();
    };
    for (var i = 0; i < self.buttonConfigs.length; i++) {
      var conf = self.buttonConfigs[i];
      var button = new Button(conf, self.onToggle);
      button.dom.style.width = config.width + "px";
      self.buttons.push(button);
      self.dom.appendChild(button.dom);
    }
    for (var i = 0; i < self.buttons.length; i++) {
      var button = self.buttons[i];
      if (button.config.selected) {
        button.turnOn();
        break;
      }
    }
  }
  function Button(buttonConfig, onChoose) {
    var self = this;
    self.config = buttonConfig;
    self.dom = document.createElement("div");
    self.dom.setAttribute("class", "button");
    self.dom.style.marginRight = buttonConfig.margin + "px";
    self.dom.innerHTML = buttonConfig.name;
    self.onClick = function () {
      onChoose(self, buttonConfig);
    };
    self.dom.onclick = self.onClick;
    self.turnOff = function () {
      self.dom.setAttribute("on", "no");
    };
    self.turnOn = function () {
      self.dom.setAttribute("on", "yes");
    };
    self.turnOff();
  }
  globalThis.ButtonGroup = ButtonGroup;
  globalThis.Button = Button;
})();
