// @generated by tools/build-play-js.ts
// Source: play/src/browser/Draggable.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/Draggable.ts
  function Draggable(config) {
    var self = this;
    self.x = config.x;
    self.y = config.y;
    self.model = config.model;
    self.radius = config.radius || 30;
    self.hitTest = function (x, y) {
      var dx = x - self.x;
      var dy = y - self.y;
      var r = self.radius;
      return dx * dx + dy * dy < r * r;
    };
    self.moveTo = function (x, y) {
      self.x = x + self.offX;
      self.y = y + self.offY;
    };
    self.offX = 0;
    self.offY = 0;
    self.startDrag = function () {
      self.offX = self.x - Mouse.x;
      self.offY = self.y - Mouse.y;
    };
    self.update = function () {};
    self.draw = function (ctx) {};
  }
  function DraggableManager(model) {
    var self = this;
    self.model = model;
    self.isOver = function () {
      for (var i = model.draggables.length - 1; i >= 0; i--) {
        var d = model.draggables[i];
        if (d.hitTest(Mouse.x, Mouse.y)) {
          return d;
        }
      }
      return null;
    };
    subscribe(model.id + "-mousemove", function () {
      if (Mouse.pressed) {
        model.update();
      } else if (self.isOver()) {
        model.canvas.setAttribute("cursor", "grab");
      } else {
        model.canvas.setAttribute("cursor", "");
      }
    });
    subscribe(model.id + "-mousedown", function () {
      Mouse.dragging = self.isOver();
      if (Mouse.dragging) {
        Mouse.dragging.startDrag();
        model.update();
        model.canvas.setAttribute("cursor", "grabbing");
      }
    });
    subscribe(model.id + "-mouseup", function () {
      Mouse.dragging = null;
    });
  }
  globalThis.Draggable = Draggable;
  globalThis.DraggableManager = DraggableManager;
})();
