// @generated by tools/build-play-js.ts
// Source: play/src/browser/Election.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/Election.ts
  var Election = {};
  var _candidateIds = function (model) {
    var ids = [];
    for (var i = 0; i < model.candidates.length; i++) {
      ids.push(model.candidates[i].id);
    }
    return ids;
  };
  Election.score = function (model, options) {
    var result = ElectionCore.score(_candidateIds(model), model.getBallots());
    var tally = result.tally;
    var winner = result.winner;
    var color = _colorWinner(model, winner);
    if (!winner) {
      var text = "<b>NOBODY WINS</b>";
      model.caption.innerHTML = text;
    } else {
      var text = "";
      text += "<span class='small'>";
      text += "<b>highest average score wins</b><br>";
      for (var i = 0; i < model.candidates.length; i++) {
        var c = model.candidates[i].id;
        text +=
          _icon(c) + "'s score: " + tally[c].toFixed(2) + " out of 5.00<br>";
      }
      text += "<br>";
      text += _icon(winner) + " has the highest score, so...<br>";
      text += "</span>";
      text += "<br>";
      text +=
        "<b style='color:" + color + "'>" + winner.toUpperCase() + "</b> WINS";
      model.caption.innerHTML = text;
    }
  };
  Election.approval = function (model, options) {
    var result = ElectionCore.approval(
      _candidateIds(model),
      model.getBallots(),
    );
    var tally = result.tally;
    var winner = result.winner;
    var color = _colorWinner(model, winner);
    if (!winner) {
      var text = "<b>NOBODY WINS</b>";
      model.caption.innerHTML = text;
    } else {
      var text = "";
      text += "<span class='small'>";
      text += "<b>most approvals wins</b><br>";
      for (var i = 0; i < model.candidates.length; i++) {
        var c = model.candidates[i].id;
        text += _icon(c) + " got " + tally[c] + " approvals<br>";
      }
      text += "<br>";
      text += _icon(winner) + " is most approved, so...<br>";
      text += "</span>";
      text += "<br>";
      text +=
        "<b style='color:" + color + "'>" + winner.toUpperCase() + "</b> WINS";
      model.caption.innerHTML = text;
    }
  };
  Election.condorcet = function (model, options) {
    var text = "";
    text += "<span class='small'>";
    text += "<b>who wins each one-on-one?</b><br>";
    var result = ElectionCore.condorcet(
      _candidateIds(model),
      model.getBallots(),
    );
    for (var i = 0; i < result.contests.length; i++) {
      var contest = result.contests[i];
      text +=
        _icon(contest.a) +
        " vs " +
        _icon(contest.b) +
        ": " +
        _icon(contest.winner) +
        " wins by " +
        contest.by +
        " to " +
        contest.to +
        "<br>";
    }
    var topWinner = result.winner;
    text += "<br>";
    if (topWinner) {
      var color = _colorWinner(model, topWinner);
      text +=
        _icon(topWinner) +
        " beats all other candidates in one-on-one races.<br>";
      text += "</span>";
      text += "<br>";
      text +=
        "<b style='color:" +
        color +
        "'>" +
        topWinner.toUpperCase() +
        "</b> WINS";
    } else {
      model.canvas.style.borderColor = "#000";
      text += "NOBODY beats everyone else in one-on-one races.<br>";
      text += "</span>";
      text += "<br>";
      text += "THERE'S NO WINNER.<br>";
      text += "<b id='ohno'>OH NO.</b>";
    }
    model.caption.innerHTML = text;
  };
  Election.borda = function (model, options) {
    var result = ElectionCore.borda(_candidateIds(model), model.getBallots());
    var tally = result.tally;
    var winner = result.winner;
    var color = _colorWinner(model, winner);
    if (!winner) {
      var text = "<b>NOBODY WINS</b>";
      model.caption.innerHTML = text;
    } else {
      var text = "";
      text += "<span class='small'>";
      text += "<b>lower score is better</b><br>";
      for (var i = 0; i < model.candidates.length; i++) {
        var c = model.candidates[i].id;
        text += _icon(c) + "'s total score: " + tally[c] + "<br>";
      }
      text += "<br>";
      text += _icon(winner) + " has the <i>lowest</i> score, so...<br>";
      text += "</span>";
      text += "<br>";
      text +=
        "<b style='color:" + color + "'>" + winner.toUpperCase() + "</b> WINS";
      model.caption.innerHTML = text;
    }
  };
  Election.irv = function (model, options) {
    var text = "";
    text += "<span class='small'>";
    var result = ElectionCore.irv(_candidateIds(model), model.getBallots());
    var finalWinner = result.winner;
    for (var r = 0; r < result.rounds.length; r++) {
      var round = result.rounds[r];
      var candidates = Object.keys(round.tally);
      text += "<b>round " + round.round + ":</b><br>";
      text += "who's voters' #1 choice?<br>";
      for (var i = 0; i < candidates.length; i++) {
        var c = candidates[i];
        text += _icon(c) + ":" + round.tally[c];
        if (i < candidates.length - 1) text += ", ";
      }
      text += "<br>";
      if (round.winner) {
        text += _icon(round.winner) + " has more than 50%<br>";
        break;
      }
      text += "nobody's more than 50%. ";
      text +=
        "eliminate loser, " + _icon(round.eliminated) + ". next round!<br><br>";
    }
    var color = _colorWinner(model, finalWinner);
    text += "</span>";
    text += "<br>";
    text +=
      "<b style='color:" +
      color +
      "'>" +
      finalWinner.toUpperCase() +
      "</b> WINS";
    model.caption.innerHTML = text;
  };
  Election.plurality = function (model, options) {
    options = options || {};
    var result = ElectionCore.plurality(
      _candidateIds(model),
      model.getBallots(),
    );
    var tally = result.tally;
    var winner = result.winner;
    var color = _colorWinner(model, winner);
    var text = "";
    text += "<span class='small'>";
    if (options.sidebar) {
      text += "<b>most votes wins</b><br>";
    }
    for (var i = 0; i < model.candidates.length; i++) {
      var c = model.candidates[i].id;
      if (options.sidebar) {
        text += _icon(c) + " got " + tally[c] + " votes<br>";
      } else {
        text += c + ": " + tally[c];
        if (options.verbose) text += " votes";
        if (i < model.candidates.length - 1) text += ", ";
      }
    }
    if (options.sidebar) {
      text += "<br>";
      text += _icon(winner) + " has most votes, so...<br>";
    }
    text += "</span>";
    text += "<br>";
    text +=
      "<b style='color:" + color + "'>" + winner.toUpperCase() + "</b> WINS";
    model.caption.innerHTML = text;
  };
  var _colorWinner = function (model, winner) {
    var color = winner ? Candidate.graphics[winner].fill : "";
    model.canvas.style.borderColor = color;
    return color;
  };
  var _seats = function (model, options) {
    options = options || {};
    return options.seats || model.seats || 5;
  };
  var _seatRow = function (seatWinners) {
    var row = "<div class='seats'>";
    for (var i = 0; i < seatWinners.length; i++) {
      row += _icon(seatWinners[i]);
    }
    row += "</div>";
    return row;
  };
  var _neutralBorder = function (model) {
    model.canvas.style.borderColor = "#999";
  };
  var _seatBar = function (model, seatsWon, totalSeats) {
    var bar = "<div class='seatbar'>";
    for (var i = 0; i < model.candidates.length; i++) {
      var c = model.candidates[i];
      var n = seatsWon[c.id] || 0;
      if (n <= 0) continue;
      var pct = ((n / totalSeats) * 100).toFixed(2);
      bar +=
        "<span style='width:" + pct + "%;background:" + c.fill + "'></span>";
    }
    bar += "</div>";
    return bar;
  };
  var _sortedScores = function (scores) {
    var rows = [];
    for (var id in scores) {
      rows.push({ id, score: scores[id] });
    }
    rows.sort(function (a, b) {
      return b.score - a.score;
    });
    return rows;
  };
  var _spavScoreRows = function (round) {
    var rows = _sortedScores(round.scores);
    var top = rows.length ? rows[0].score : 0;
    var limit = Math.min(rows.length, 3);
    var text = "<div class='spav-scores'>";
    for (var i = 0; i < limit; i++) {
      var row = rows[i];
      var pct = top ? (row.score / top) * 100 : 0;
      text +=
        "<div class='spav-score-row" +
        (row.id === round.winner ? " winning" : "") +
        "'>";
      text += "<span class='spav-score-icon'>" + _icon(row.id) + "</span>";
      text +=
        "<span class='spav-score-bar'><span style='width:" +
        pct.toFixed(1) +
        "%;background:" +
        Candidate.graphics[row.id].fill +
        "'></span></span>";
      text +=
        "<span class='spav-score-num'>" +
        row.score.toFixed(1) +
        (row.id === round.winner ? " ✓" : "") +
        "</span>";
      text += "</div>";
    }
    if (rows.length > limit) {
      text +=
        "<div class='spav-more'>+" + (rows.length - limit) + " more</div>";
    }
    text += "</div>";
    return text;
  };
  var _stvFlowLabel = function (flow) {
    if (flow.action == "elected") {
      return "keeps a quota; surplus transfers";
    }
    return "eliminated; votes transfer";
  };
  var _stvTarget = function (from, transfer) {
    if (transfer.to == "elected") {
      return {
        icon: "<span class='stv-seat'>seat</span>",
        color: Candidate.graphics[from].fill,
      };
    }
    if (transfer.to == "exhausted") {
      return {
        icon: "<span class='stv-exhausted'>none</span>",
        color: "#bbb",
      };
    }
    return {
      icon: _icon(transfer.to),
      color: Candidate.graphics[transfer.to].fill,
    };
  };
  var _stvSankey = function (result) {
    var flows = result.flows || [];
    if (!flows.length) return "";
    var text = "<div class='stv-sankey'>";
    text += "<div class='stv-sankey-title'>how votes move</div>";
    for (var i = 0; i < flows.length; i++) {
      var flow = flows[i];
      var transfers = flow.transfers || [];
      var height = Math.max(42, transfers.length * 24);
      var maxValue = Math.max(flow.votes || 1, result.quota || 1);
      var mid = height / 2;
      text += "<div class='stv-flow-step'>";
      text +=
        "<div class='stv-flow-from'>" +
        _icon(flow.from) +
        "<span>" +
        _stvFlowLabel(flow) +
        "</span></div>";
      text +=
        "<svg class='stv-flow-svg' viewBox='0 0 180 " +
        height +
        "' aria-hidden='true'>";
      for (var j = 0; j < transfers.length; j++) {
        var transfer = transfers[j];
        var target = _stvTarget(flow.from, transfer);
        var y = transfers.length == 1 ? mid : 12 + j * 24;
        var width = Math.max(2, Math.min(18, (transfer.value / maxValue) * 18));
        text +=
          "<path d='M 8 " +
          mid.toFixed(1) +
          " C 64 " +
          mid.toFixed(1) +
          ", 112 " +
          y.toFixed(1) +
          ", 172 " +
          y.toFixed(1) +
          "' stroke='" +
          target.color +
          "' stroke-width='" +
          width.toFixed(1) +
          "'/>";
      }
      text += "</svg>";
      text += "<div class='stv-flow-to' style='min-height:" + height + "px'>";
      for (var k = 0; k < transfers.length; k++) {
        var row = transfers[k];
        var rowTarget = _stvTarget(flow.from, row);
        text +=
          "<div class='stv-flow-target'>" +
          rowTarget.icon +
          "<b>" +
          row.value.toFixed(row.value >= 10 ? 0 : 1) +
          "</b></div>";
      }
      text += "</div></div>";
    }
    text += "</div>";
    return text;
  };
  Election.partylist = function (model, options) {
    var seats = _seats(model, options);
    _neutralBorder(model);
    var result = ElectionCore.partyList(
      _candidateIds(model),
      model.getBallots(),
      seats,
    );
    var tally = result.tally;
    var seatsWon = result.seatsWon;
    var seatWinners = result.seatWinners;
    var place = seats >= 50 ? "parliament" : "constituency";
    var text = "";
    text += "<b>" + (seats >= 50 ? "seats:" : "elected:") + "</b>";
    text += "<div class='seats partylist-result'>";
    if (seats < 50) {
      for (var s = 0; s < seatWinners.length; s++) {
        text += _icon(seatWinners[s]);
      }
    }
    text += _seatBar(model, seatsWon, seats);
    text += "</div>";
    text += "<div class='small'>";
    text += "<b>seats shared out in proportion to each party's votes</b><br>";
    text += "(a " + seats + "-seat " + place + ")<br><br>";
    if (seats >= 50) {
      text += "<div class='pl-seat-counts'>";
    }
    for (var i = 0; i < model.candidates.length; i++) {
      var c = model.candidates[i].id;
      if (seats >= 50) {
        text += "<div class='pl-seat-count'>";
      }
      text +=
        _icon(c) +
        " <b>" +
        seatsWon[c] +
        "</b> seat" +
        (seatsWon[c] == 1 ? "" : "s");
      text += seats >= 50 ? "</div>" : "<br>";
    }
    if (seats >= 50) {
      text += "</div>";
    }
    text += "</div>";
    model.caption.innerHTML = text;
  };
  Election.spav = function (model, options) {
    var seats = _seats(model, options);
    _neutralBorder(model);
    var result = ElectionCore.spav(
      _candidateIds(model),
      model.getBallots(),
      seats,
    );
    var elected = result.elected;
    var text = "<b>elected:</b>";
    text += _seatRow(elected);
    text += "<div class='small'>";
    text += "<b>each seat is filled by reweighted approvals</b><br>";
    text +=
      "after a winner, ballots that approved them count for less next round.<br><br>";
    for (var s = 0; s < result.rounds.length; s++) {
      var round = result.rounds[s];
      text += "<div class='spav-round'>";
      text +=
        "<b>seat " + round.seat + ":</b> " + _icon(round.winner) + " wins";
      text += _spavScoreRows(round);
      text += "</div>";
    }
    text += "</div>";
    model.caption.innerHTML = text;
  };
  Election.stv = function (model, options) {
    var seats = _seats(model, options);
    _neutralBorder(model);
    var result = ElectionCore.stv(
      _candidateIds(model),
      model.getBallots(),
      seats,
    );
    var quota = result.quota;
    var elected = result.elected;
    var text = "<b>elected:</b>";
    text += _seatRow(elected);
    text += "<span class='small'>";
    text += "<b>quota to win a seat: " + quota + "</b>";
    text += "</span>";
    text += _stvSankey(result);
    model.caption.innerHTML = text;
  };
  globalThis.Election = Election;
})();
