// @generated by tools/build-play-js.ts
// Source: play/src/browser/helpers.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/helpers.ts
  Math.TAU = Math.PI * 2;
  function _icon(name) {
    var g = typeof Candidate !== "undefined" ? Candidate.graphics[name] : null;
    if (g && !g.img) {
      return Candidate.svgFor(name);
    }
    return "<img src='img/icon/" + name + ".png'/>";
  }
  globalThis._icon = _icon;
})();
