// @generated by tools/build-play-js.ts
// Source: play/src/browser/Loader.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/Loader.ts
  window.Loader = {};
  Loader.load = function (imagePaths) {
    var assetsToLoad = imagePaths.length;
    var _onAssetLoad = function () {
      assetsToLoad--;
      if (assetsToLoad == 0) {
        Loader.onload();
      }
    };
    for (var i = 0; i < imagePaths.length; i++) {
      var img = new Image();
      img.onload = _onAssetLoad;
      img.src = imagePaths[i];
    }
  };
  globalThis.Loader = Loader;
})();
