// @generated by tools/build-play-js.ts
// Source: play/src/browser/main_ballot.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/main_ballot.ts
  window.ONLY_ONCE = false;
  function main(ballotType) {
    if (ONLY_ONCE) return;
    ONLY_ONCE = true;
    var VoterType = window[ballotType + "Voter"];
    var BallotType = window[ballotType + "Ballot"];
    Loader.onload = function () {
      window.model = new Model({ size: 250, border: 2 });
      document.body.appendChild(model.dom);
      model.onInit = function () {
        model.addVoters({
          dist: SingleVoter,
          type: VoterType,
          x: 81,
          y: 92,
        });
        model.addCandidate("square", 41, 50);
        model.addCandidate("triangle", 153, 95);
        model.addCandidate("hexagon", 216, 216);
      };
      window.ballot = new BallotType();
      document.body.appendChild(ballot.dom);
      model.onUpdate = function () {
        ballot.update(model.voters[0].ballot);
      };
      model.init();
    };
    Loader.load([
      "img/voter_face.png",
      "img/square.png",
      "img/triangle.png",
      "img/hexagon.png",
      "img/ballot_fptp.png",
      "img/ballot_ranked.png",
      "img/ballot_approval.png",
      "img/ballot_range.png",
      "img/ballot_box.png",
      "img/ballot_rate.png",
    ]);
  }
  globalThis.main = main;
})();
