// @generated by tools/build-play-js.ts
// Source: play/src/browser/Model.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/Model.ts
  function Model(config) {
    var self = this;
    config = config || {};
    self.id = config.id || "model";
    self.size = config.size || 300;
    self.scale = config.scale || 1;
    self.border = config.border || 10;
    var canvas = document.createElement("canvas");
    canvas.setAttribute("class", "interactive");
    canvas.width = canvas.height = self.size * 2;
    canvas.style.width = canvas.style.height = self.size + "px";
    canvas.style.borderWidth = self.border + "px";
    var ctx = canvas.getContext("2d");
    self.canvas = canvas;
    self.ctx = ctx;
    self.dom = document.createElement("div");
    self.dom.setAttribute("class", "model");
    self.dom.style.width = self.size + 2 * self.border + "px";
    self.title = document.createElement("div");
    self.title.id = "title";
    self.caption = document.createElement("div");
    self.caption.id = "caption";
    self.caption.style.width = self.dom.style.width;
    self.dom.appendChild(self.title);
    self.dom.appendChild(self.canvas);
    self.dom.appendChild(self.caption);
    self.mouse = new Mouse(self.id, self.canvas);
    self.draggables = [];
    self.draggableManager = new DraggableManager(self);
    self.candidates = [];
    self.candidatesById = {};
    self.voters = [];
    self.addCandidate = function (id, x, y) {
      var candidate = new Candidate({
        model: self,
        id,
        x,
        y,
      });
      self.candidates.push(candidate);
      self.draggables.push(candidate);
      self.candidatesById[id] = candidate;
    };
    self.addVoters = function (config2) {
      config2.model = self;
      var DistClass = config2.dist;
      var voters = new DistClass(config2);
      self.voters.push(voters);
      self.draggables.push(voters);
    };
    self.onInit = function () {};
    self.init = function () {
      self.onInit();
      self.update();
    };
    self.reset = function (noInit) {
      self.candidates = [];
      self.candidatesById = {};
      self.voters = [];
      self.draggables = [];
      if (!noInit) self.init();
    };
    self.onUpdate = function () {};
    self.update = function () {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      if (Mouse.dragging) {
        Mouse.dragging.moveTo(Mouse.x, Mouse.y);
      }
      for (var i = 0; i < self.voters.length; i++) {
        var voter = self.voters[i];
        voter.update();
        voter.draw(ctx);
      }
      for (var i = 0; i < self.candidates.length; i++) {
        var c = self.candidates[i];
        c.update();
        c.draw(ctx);
      }
      self.onUpdate();
      publish(self.id + "-update");
    };
    self.getBallots = function () {
      var ballots = [];
      for (var i = 0; i < self.voters.length; i++) {
        var voter = self.voters[i];
        ballots = ballots.concat(voter.ballots);
      }
      return ballots;
    };
    self.getTotalVoters = function () {
      var count = 0;
      for (var i = 0; i < self.voters.length; i++) {
        var voter = self.voters[i];
        count += voter.points.length;
      }
      return count;
    };
  }
  globalThis.Model = Model;
})();
