// @generated by tools/build-play-js.ts
// Source: play/src/browser/Voters.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // play/src/browser/Voters.ts
  function ScoreVoter(model) {
    var self = this;
    self.model = model;
    self.radiusStep = window.HACK_BIG_RANGE ? 74 : 30;
    self.getScore = function (x) {
      var step = self.radiusStep;
      if (x < step) return 5;
      if (x < step * 2) return 4;
      if (x < step * 3) return 3;
      if (x < step * 4) return 2;
      if (step * 4 < x) return 1;
    };
    self.getBallot = function (x, y) {
      var scores = {};
      for (var i = 0; i < self.model.candidates.length; i++) {
        var c = self.model.candidates[i];
        var dx = c.x - x;
        var dy = c.y - y;
        var dist = Math.sqrt(dx * dx + dy * dy);
        scores[c.id] = self.getScore(dist);
      }
      return scores;
    };
    self.drawBG = function (ctx, x, y, ballot) {
      x = x * 2;
      y = y * 2;
      for (var i = 1; i < 5; i++) {
        ctx.beginPath();
        ctx.arc(x, y, self.radiusStep * i * 2, 0, Math.TAU, false);
        ctx.lineWidth = (5 - i) * 2;
        ctx.strokeStyle = "#888";
        ctx.stroke();
      }
    };
    self.drawCircle = function (ctx, x, y, size, ballot) {
      var totalSlices = self.model.candidates.length * 4;
      var leftover = totalSlices;
      var slices = [];
      for (var i = 0; i < self.model.candidates.length; i++) {
        var c = self.model.candidates[i];
        var cID = c.id;
        var score = ballot[cID] - 1;
        leftover -= score;
        slices.push({
          num: score,
          fill: c.fill,
        });
      }
      slices.push({
        num: leftover,
        fill: "#bbb",
      });
      _drawSlices(ctx, x, y, size, slices, totalSlices);
    };
  }
  function ApprovalVoter(model) {
    var self = this;
    self.model = model;
    self.approvalRadius = 100;
    self.getBallot = function (x, y) {
      var approved = [];
      for (var i = 0; i < self.model.candidates.length; i++) {
        var c = self.model.candidates[i];
        var dx = c.x - x;
        var dy = c.y - y;
        var dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < self.approvalRadius) {
          approved.push(c.id);
        }
      }
      return { approved };
    };
    self.drawBG = function (ctx, x, y, ballot) {
      x = x * 2;
      y = y * 2;
      ctx.beginPath();
      ctx.arc(x, y, self.approvalRadius * 2, 0, Math.TAU, false);
      ctx.lineWidth = 8;
      ctx.strokeStyle = "#888";
      ctx.stroke();
    };
    self.drawCircle = function (ctx, x, y, size, ballot) {
      var slices = [];
      if (ballot.approved.length == 0) {
        _drawBlank(ctx, x, y, size);
        return;
      }
      for (var i = 0; i < ballot.approved.length; i++) {
        var candidate = self.model.candidatesById[ballot.approved[i]];
        slices.push({ num: 1, fill: candidate.fill });
      }
      _drawSlices(ctx, x, y, size, slices, ballot.approved.length);
    };
  }
  function RankedVoter(model) {
    var self = this;
    self.model = model;
    self.getBallot = function (x, y) {
      var rank = [];
      for (var i = 0; i < self.model.candidates.length; i++) {
        rank.push(self.model.candidates[i].id);
      }
      rank = rank.sort(function (a, b) {
        var c1 = self.model.candidatesById[a];
        var x1 = c1.x - x;
        var y1 = c1.y - y;
        var d1 = x1 * x1 + y1 * y1;
        var c2 = self.model.candidatesById[b];
        var x2 = c2.x - x;
        var y2 = c2.y - y;
        var d2 = x2 * x2 + y2 * y2;
        return d1 - d2;
      });
      return { rank };
    };
    self.drawBG = function (ctx, x, y, ballot) {
      x = x * 2;
      y = y * 2;
      for (var i = 0; i < ballot.rank.length; i++) {
        var lineWidth = ((ballot.rank.length - i) / ballot.rank.length) * 8;
        var rank = ballot.rank[i];
        var c = self.model.candidatesById[rank];
        var cx = c.x * 2;
        var cy = c.y * 2;
        ctx.beginPath();
        ctx.moveTo(x, y);
        ctx.lineTo(cx, cy);
        ctx.lineWidth = lineWidth;
        ctx.strokeStyle = "#888";
        ctx.stroke();
      }
    };
    self.drawCircle = function (ctx, x, y, size, ballot) {
      var slices = [];
      var n = ballot.rank.length;
      var totalSlices = (n * (n + 1)) / 2;
      for (var i = 0; i < ballot.rank.length; i++) {
        var rank = ballot.rank[i];
        var candidate = self.model.candidatesById[rank];
        slices.push({ num: n - i, fill: candidate.fill });
      }
      _drawSlices(ctx, x, y, size, slices, totalSlices);
    };
  }
  function PluralityVoter(model) {
    var self = this;
    self.model = model;
    self.getBallot = function (x, y) {
      var closest = null;
      var closestDistance = Infinity;
      for (var j = 0; j < self.model.candidates.length; j++) {
        var c = self.model.candidates[j];
        var dx = c.x - x;
        var dy = c.y - y;
        var dist = dx * dx + dy * dy;
        if (dist < closestDistance) {
          closestDistance = dist;
          closest = c;
        }
      }
      return { vote: closest.id };
    };
    self.drawBG = function (ctx, x, y, ballot) {
      var candidate = model.candidatesById[ballot.vote];
      x = x * 2;
      y = y * 2;
      var tx = candidate.x * 2;
      var ty = candidate.y * 2;
      ctx.beginPath();
      ctx.moveTo(x, y);
      ctx.lineTo(tx, ty);
      ctx.lineWidth = 8;
      ctx.strokeStyle = "#888";
      ctx.stroke();
    };
    self.drawCircle = function (ctx, x, y, size, ballot) {
      x = x * 2;
      y = y * 2;
      var fill = Candidate.graphics[ballot.vote].fill;
      ctx.fillStyle = fill;
      ctx.beginPath();
      ctx.arc(x, y, size, 0, Math.TAU, true);
      ctx.fill();
    };
  }
  var _drawSlices = function (ctx, x, y, size, slices, totalSlices) {
    x = x * 2;
    y = y * 2;
    var startingAngle = -Math.TAU / 4;
    var endingAngle = 0;
    for (var i = 0; i < slices.length; i++) {
      var slice = slices[i];
      var sliceAngle = slice.num * (Math.TAU / totalSlices);
      endingAngle = startingAngle + sliceAngle;
      ctx.fillStyle = slice.fill;
      ctx.beginPath();
      ctx.moveTo(x, y);
      ctx.arc(x, y, size, startingAngle, endingAngle, false);
      ctx.lineTo(x, y);
      ctx.closePath();
      ctx.fill();
      startingAngle = endingAngle;
    }
  };
  var _drawBlank = function (ctx, x, y, size) {
    var slices = [{ num: 1, fill: "#bbb" }];
    _drawSlices(ctx, x, y, size, slices, 1);
  };
  function GaussianVoters(config) {
    var self = this;
    Draggable.call(self, config);
    self.num = config.num || 3;
    self.type = new config.type(self.model);
    self.setType = function (newType) {
      self.type = new newType(self.model);
    };
    self.radius = 50;
    var spacings = [0, 10, 11, 12, 15, 20, 30, 50, 100];
    if (self.num == 1) {
      spacings.splice(4);
    }
    if (self.num == 2) {
      spacings.splice(5);
    }
    var points = [[0, 0]];
    self.points = points;
    var _radius = 0,
      _RINGS = spacings.length;
    for (var i = 1; i < _RINGS; i++) {
      var spacing = spacings[i];
      _radius += spacing;
      var circum = Math.TAU * _radius;
      var num = Math.floor(circum / spacing);
      if (i == _RINGS - 1) num += 3;
      var err = 0.01;
      for (var angle = 0; angle < Math.TAU - err; angle += Math.TAU / num) {
        var x = Math.cos(angle) * _radius;
        var y = Math.sin(angle) * _radius;
        points.push([x, y]);
      }
    }
    self.ballots = [];
    self.update = function () {
      self.ballots = [];
      for (var i2 = 0; i2 < points.length; i2++) {
        var p = points[i2];
        var x2 = self.x + p[0];
        var y2 = self.y + p[1];
        var ballot = self.type.getBallot(x2, y2);
        self.ballots.push(ballot);
      }
    };
    self.draw = function (ctx) {
      for (var i2 = 0; i2 < points.length; i2++) {
        var p = points[i2];
        var x2 = self.x + p[0];
        var y2 = self.y + p[1];
        var ballot = self.ballots[i2];
        self.type.drawCircle(ctx, x2, y2, 10, ballot);
      }
    };
  }
  function SingleVoter(config) {
    var self = this;
    Draggable.call(self, config);
    self.type = new config.type(self.model);
    self.img = new Image();
    self.img.src = "img/voter_face.png";
    self.ballot = null;
    self.update = function () {
      self.ballot = self.type.getBallot(self.x, self.y);
    };
    self.draw = function (ctx) {
      self.type.drawBG(ctx, self.x, self.y, self.ballot);
      var size = 20;
      self.type.drawCircle(ctx, self.x, self.y, size, self.ballot);
      size = size * 2;
      var x = self.x * 2;
      var y = self.y * 2;
      ctx.drawImage(self.img, x - size / 2, y - size / 2, size, size);
    };
  }
  globalThis.ScoreVoter = ScoreVoter;
  globalThis.ApprovalVoter = ApprovalVoter;
  globalThis.RankedVoter = RankedVoter;
  globalThis.PluralityVoter = PluralityVoter;
  globalThis.GaussianVoters = GaussianVoters;
  globalThis.SingleVoter = SingleVoter;
})();
