import { writeFile } from "node:fs/promises";
import { buildEntries } from "./build-entries";

const generatedBanner = (entrypoint: string) =>
  [
    "// @generated by tools/build-play-js.ts",
    `// Source: ${entrypoint}`,
    "// Do not edit this file directly; edit the source file instead.",
    "",
  ].join("\n");

for (const entry of buildEntries) {
  const result = await Bun.build({
    entrypoints: [entry.entrypoint],
    target: "browser",
    format: "iife",
  });

  if (!result.success) {
    for (const log of result.logs) {
      console.error(log);
    }
    process.exit(1);
  }

  const output = await result.outputs[0].text();
  await writeFile(entry.outfile, generatedBanner(entry.entrypoint) + output);

  console.log(`Built ${entry.outfile}`);
}
