// @generated by tools/build-play-js.ts
// Source: splash/src/splash.ts
// Do not edit this file directly; edit the source file instead.
(() => {
  // splash/src/splash.ts
  Loader.onload = function () {
    var width = 1500;
    var height = 400;
    var canvas = document.createElement("canvas");
    canvas.width = width * 2;
    canvas.height = height * 2;
    canvas.style.width = width + "px";
    canvas.style.height = height + "px";
    var ctx = canvas.getContext("2d");
    document.body.appendChild(canvas);
    var mouse = new Mouse("splash", canvas);
    var grid = [];
    var SIZE = 25;
    var w = width / SIZE;
    var h = height / SIZE;
    for (var y = 0; y < h; y++) {
      var row = [];
      grid.push(row);
      for (var x = 0; x < w; x++) {
        var state = Math.floor(Math.random() * 3);
        row.push(state);
      }
    }
    var _getNeighbors = function (initX, initY, targetState) {
      var neighbors = [];
      for (var y2 = initY - 1; y2 <= initY + 1; y2++) {
        if (y2 < 0) continue;
        if (y2 > h - 1) continue;
        for (var x2 = initX - 1; x2 <= initX + 1; x2++) {
          if (x2 < 0) continue;
          if (x2 > w - 1) continue;
          var state2 = grid[y2][x2];
          if (targetState == -1 || state2 == targetState) {
            neighbors.push([x2, y2]);
          }
        }
      }
      return neighbors;
    };
    var _update = function () {
      if (!window.isOnScreen) return;
      var positions = [];
      for (var y2 = 0; y2 < h; y2++) {
        for (var x2 = 0; x2 < w; x2++) {
          positions.push([x2, y2]);
        }
      }
      positions = positions.sort(function () {
        return Math.random() < 0.5;
      });
      for (var i = 0; i < positions.length; i++) {
        var pos = positions[i];
        var x2 = pos[0];
        var y2 = pos[1];
        var state2 = grid[y2][x2];
        var targetState;
        if (state2 == 0) targetState = 1;
        if (state2 == 1) targetState = 2;
        if (state2 == 2) targetState = 0;
        var neighbors = _getNeighbors(x2, y2, targetState);
        if (neighbors.length == 0) continue;
        var target = neighbors[Math.floor(Math.random() * neighbors.length)];
        x2 = target[0];
        y2 = target[1];
        grid[y2][x2] = state2;
      }
      if (Mouse.x && Mouse.y) {
        var x2 = Math.floor(Mouse.x / SIZE);
        var y2 = Math.floor(Mouse.y / SIZE);
        var neighbors = _getNeighbors(x2, y2, -1);
        for (var i = 0; i < neighbors.length; i++) {
          var pos = neighbors[i];
          x2 = pos[0];
          y2 = pos[1];
          grid[y2][x2] = Math.floor(Math.random() * 3);
        }
      }
      _draw();
    };
    setInterval(_update, 50);
    var img = new Image();
    img.src = "vote.png";
    var _draw = function () {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      for (var y2 = 0; y2 < h; y2++) {
        for (var x2 = 0; x2 < w; x2++) {
          var state2 = grid[y2][x2];
          ctx.drawImage(
            img,
            state2 * SIZE * 2,
            0,
            SIZE * 2,
            SIZE * 2,
            x2 * SIZE * 2,
            y2 * SIZE * 2,
            SIZE * 2,
            SIZE * 2,
          );
        }
      }
    };
    _draw();
  };
  Loader.load(["vote.png"]);
  window.isOnScreen = true;
  window.addEventListener(
    "message",
    function (event) {
      window.isOnScreen = event.data.isOnScreen;
    },
    false,
  );
})();
